#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;

if ( ! file_exists('vendor/autoload.php') ) {
	echo "ERROR: You need to install this project with Composer. See the readme file.".PHP_EOL.PHP_EOL;
	exit;
}

require 'vendor/autoload.php';

$app = new Application('Delorean Time Machine', '1.0');

$app->add(new Coderdojo\Delorean\ScreenshotCommand);

$app->run();